import Home from "./Home"
import Notes from "./Notes"
import Landing from "./Landing"
import Test from "./Test"
import Doubts from "./Doubts"
import Subject from "./Subject"
import Post from "./Post"
import Todo from "./Todo"
import Login from "./Login"
export {Home,Notes,Landing,Test, Doubts, Subject,Todo,Login, Post}